# Generated by Django 4.0.4 on 2022-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip',
            field=models.GenericIPAddressField(auto_created=True, blank=True, null=True),
        ),
    ]
