# Generated by Django 4.0.4 on 2022-04-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auditlog_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
